[package]
name = "mumble-protocol"
version = "0.0.0"
edition = "2015"

[lib]
path = "lib.rs"

[dependencies]
protobuf = "2.0.4"
byteorder = "1.1.0"
bitflags = "1.0.1"

[build-dependencies]
protoc-rust = "2.0.4"
